"""abandon Table blog_music

Revision ID: 05328f9debe5
Revises: 9959c72c980d
Create Date: 2026-06-01 17:05:39.869765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05328f9debe5'
down_revision: Union[str, Sequence[str], None] = '9959c72c980d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs_music')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs_music',
    sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('music_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], name=op.f('blogs_music_blog_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], name=op.f('blogs_music_music_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('blog_id', 'music_id', name=op.f('blogs_music_pkey'))
    )
    # ### end Alembic commands ###
