"""update Table music

Revision ID: 094376ce390a
Revises: 1beb67a08ef8
Create Date: 2026-02-18 09:14:44.289199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094376ce390a'
down_revision: Union[str, Sequence[str], None] = '1beb67a08ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'audio',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='音频URL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'audio',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='音频URL')
    # ### end Alembic commands ###
