"""create Table blog_likes blog_favorites music_favorites

Revision ID: 100935cd1c85
Revises: 7755e31d57c6
Create Date: 2026-03-12 11:17:35.680868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100935cd1c85'
down_revision: Union[str, Sequence[str], None] = '7755e31d57c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_favorites',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cycle=False), nullable=False, comment='博客收藏记录id'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='收藏用户通用id'),
    sa.Column('blog_id', sa.Integer(), nullable=False, comment='被收藏博客id'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='收藏时间'),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.reks_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'blog_id', name='uq_blog_favorites_user_blog')
    )
    op.create_index('ix_blog_favorites_blog_created', 'blog_favorites', ['blog_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_blog_favorites_blog_id'), 'blog_favorites', ['blog_id'], unique=False)
    op.create_index(op.f('ix_blog_favorites_id'), 'blog_favorites', ['id'], unique=True)
    op.create_index(op.f('ix_blog_favorites_user_id'), 'blog_favorites', ['user_id'], unique=False)
    op.create_table('blog_likes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cycle=False), nullable=False, comment='点赞记录id'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='点赞用户通用id'),
    sa.Column('blog_id', sa.Integer(), nullable=False, comment='被点赞博客id'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='点赞时间'),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.reks_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'blog_id', name='uq_blog_likes_user_blog')
    )
    op.create_index('ix_blog_likes_blog_created', 'blog_likes', ['blog_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_blog_likes_blog_id'), 'blog_likes', ['blog_id'], unique=False)
    op.create_index(op.f('ix_blog_likes_id'), 'blog_likes', ['id'], unique=True)
    op.create_index(op.f('ix_blog_likes_user_id'), 'blog_likes', ['user_id'], unique=False)
    op.create_table('music_favorites',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cycle=False), nullable=False, comment='音乐收藏记录id'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='收藏用户通用id'),
    sa.Column('music_id', sa.Integer(), nullable=False, comment='被收藏音乐id'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='收藏时间'),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.reks_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'music_id', name='uq_music_favorites_user_music')
    )
    op.create_index(op.f('ix_music_favorites_id'), 'music_favorites', ['id'], unique=True)
    op.create_index('ix_music_favorites_music_created', 'music_favorites', ['music_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_music_favorites_music_id'), 'music_favorites', ['music_id'], unique=False)
    op.create_index(op.f('ix_music_favorites_user_id'), 'music_favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_music_favorites_user_id'), table_name='music_favorites')
    op.drop_index(op.f('ix_music_favorites_music_id'), table_name='music_favorites')
    op.drop_index('ix_music_favorites_music_created', table_name='music_favorites')
    op.drop_index(op.f('ix_music_favorites_id'), table_name='music_favorites')
    op.drop_table('music_favorites')
    op.drop_index(op.f('ix_blog_likes_user_id'), table_name='blog_likes')
    op.drop_index(op.f('ix_blog_likes_id'), table_name='blog_likes')
    op.drop_index(op.f('ix_blog_likes_blog_id'), table_name='blog_likes')
    op.drop_index('ix_blog_likes_blog_created', table_name='blog_likes')
    op.drop_table('blog_likes')
    op.drop_index(op.f('ix_blog_favorites_user_id'), table_name='blog_favorites')
    op.drop_index(op.f('ix_blog_favorites_id'), table_name='blog_favorites')
    op.drop_index(op.f('ix_blog_favorites_blog_id'), table_name='blog_favorites')
    op.drop_index('ix_blog_favorites_blog_created', table_name='blog_favorites')
    op.drop_table('blog_favorites')
    # ### end Alembic commands ###
