"""create blogs tags blogs-tags table 

Revision ID: 145cb0232ecf
Revises: 2a84d28322f5
Create Date: 2026-01-23 12:12:45.545830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '145cb0232ecf'
down_revision: Union[str, Sequence[str], None] = '2a84d28322f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cycle=False), nullable=False, comment='博客id'),
    sa.Column('type', sa.Enum('draft', 'publish', name='blogenum'), nullable=False, comment='0草稿 1正式'),
    sa.Column('state', sa.Enum('normal', 'delete', 'ban', name='blogstateenum'), nullable=False, comment='0正常 1已删除 2被封禁'),
    sa.Column('title', sa.String(length=40), nullable=False, comment='博客标题'),
    sa.Column('content', sa.TEXT(), nullable=False, comment='博客内容'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogs_id'), 'blogs', ['id'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cycle=False), nullable=False, comment='标签id'),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=True)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('blogs_tags',
    sa.Column('blog_id', sa.Integer(), nullable=False, comment='Blog ID'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='Tag ID'),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs_tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_blogs_id'), table_name='blogs')
    op.drop_table('blogs')
    # ### end Alembic commands ###
