"""check unpublish new items && update default value of 'state' in Music

Revision ID: 1701d678ff5f
Revises: 1e47c79e142f
Create Date: 2026-03-05 09:43:03.536485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1701d678ff5f'
down_revision: Union[str, Sequence[str], None] = '1e47c79e142f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
