"""update Table blog

Revision ID: 1beb67a08ef8
Revises: 23ac7af382f5
Create Date: 2026-02-14 12:09:22.517487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1beb67a08ef8'
down_revision: Union[str, Sequence[str], None] = '23ac7af382f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('cover', sa.JSON(), server_default='["https://picsum.photos/seed/picsum/200/300"]', nullable=False, comment='封面URL集合'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'cover')
    # ### end Alembic commands ###
