"""check unpublish new items && update default value of 'state' in Music

Revision ID: 1e47c79e142f
Revises: aef4f9363f70
Create Date: 2026-03-05 09:41:39.307814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e47c79e142f'
down_revision: Union[str, Sequence[str], None] = 'aef4f9363f70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'state',
               existing_type=sa.VARCHAR(length=7),
               comment='0草稿 1发布 2已删除 3被封禁',
               existing_comment='0正常 1已删除 2被封禁',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'state',
               existing_type=sa.VARCHAR(length=7),
               comment='0正常 1已删除 2被封禁',
               existing_comment='0草稿 1发布 2已删除 3被封禁',
               existing_nullable=True)
    # ### end Alembic commands ###
