"""try to fix error in ImgEnum

Revision ID: 208fbc5f1d67
Revises: 546c36fb5ce2
Create Date: 2026-01-27 11:47:28.440461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208fbc5f1d67'
down_revision: Union[str, Sequence[str], None] = '546c36fb5ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
