"""update StatusEnum

Revision ID: 23ac7af382f5
Revises: 3a29e494cee3
Create Date: 2026-02-05 14:23:12.555733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23ac7af382f5'
down_revision: Union[str, Sequence[str], None] = '3a29e494cee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('active', 'danger', 'block', name='statusenum'),
               comment='0正常 1危险 2封禁 3注销',
               existing_comment='0正常 1危险 2封禁',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('active', 'danger', 'block', name='statusenum'),
               comment='0正常 1危险 2封禁',
               existing_comment='0正常 1危险 2封禁 3注销',
               existing_nullable=False)
    # ### end Alembic commands ###
