"""update StatusEnum:danger-1 block-2

Revision ID: 2a84d28322f5
Revises: 44720e4c9609
Create Date: 2026-01-19 08:18:51.402834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a84d28322f5'
down_revision: Union[str, Sequence[str], None] = '44720e4c9609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('active', 'blocked', 'inactive', name='statusenum'),
               comment='0正常 1危险 2封禁',
               existing_comment='0正常 1禁用 2未激活',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('active', 'blocked', 'inactive', name='statusenum'),
               comment='0正常 1禁用 2未激活',
               existing_comment='0正常 1危险 2封禁',
               existing_nullable=False)
    # ### end Alembic commands ###
