"""create relationship Table blogs_music

Revision ID: 3a29e494cee3
Revises: b032c5c9cd5d
Create Date: 2026-02-03 10:44:39.211251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a29e494cee3'
down_revision: Union[str, Sequence[str], None] = 'b032c5c9cd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs_music',
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('blog_id', 'music_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs_music')
    # ### end Alembic commands ###
