"""fix SAWaring,add reks_id into User

Revision ID: 3a49b56ecea4
Revises: 39eef200dc33
Create Date: 2025-12-11 14:26:57.475598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a49b56ecea4'
down_revision: Union[str, Sequence[str], None] = '39eef200dc33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reks_id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cycle=False), nullable=False, comment='用户通用id'))
    op.create_index(op.f('ix_users_reks_id'), 'users', ['reks_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reks_id'), table_name='users')
    op.drop_column('users', 'reks_id')
    # ### end Alembic commands ###
