"""create Table music,playlist,playlists_music

Revision ID: 3b5b02dbfc60
Revises: 7ae4a81032a3
Create Date: 2026-01-29 18:57:06.336267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b5b02dbfc60'
down_revision: Union[str, Sequence[str], None] = '7ae4a81032a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music',
    sa.Column('id', sa.Integer(), nullable=False, comment='音频id'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='音频名称'),
    sa.Column('rid', sa.Integer(), nullable=False, comment='用户通用id'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('state', sa.Enum('normal', 'delete', 'ban', name='blogstateenum', native_enum=False), nullable=False, comment='0正常 1已删除 2被封禁'),
    sa.Column('original', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否原创'),
    sa.Column('cover', sa.String(), server_default='https://picsum.photos/seed/picsum/200/300', nullable=False, comment='封面URL'),
    sa.Column('audio', sa.String(), nullable=False, comment='音频URL'),
    sa.Column('desc', sa.String(length=30), nullable=True, comment='简介'),
    sa.ForeignKeyConstraint(['rid'], ['users.reks_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_name'), 'music', ['name'], unique=False)
    op.create_index(op.f('ix_music_rid'), 'music', ['rid'], unique=False)
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False, comment='歌单id'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='歌单标题'),
    sa.Column('cover', sa.String(length=500), nullable=True, comment='封面URL'),
    sa.Column('desc', sa.String(length=500), nullable=True, comment='简介'),
    sa.Column('is_private', sa.Boolean(), nullable=False, comment='是否私密'),
    sa.Column('rid', sa.Integer(), nullable=False, comment='用户通用id'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rid'], ['users.reks_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_rid'), 'playlist', ['rid'], unique=False)
    op.create_table('playlists_music',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'music_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlists_music')
    op.drop_index(op.f('ix_playlist_rid'), table_name='playlist')
    op.drop_table('playlist')
    op.drop_index(op.f('ix_music_rid'), table_name='music')
    op.drop_index(op.f('ix_music_name'), table_name='music')
    op.drop_table('music')
    # ### end Alembic commands ###
