"""change avatar into nullable

Revision ID: 44720e4c9609
Revises: abbf081957d0
Create Date: 2025-12-25 14:07:56.815037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44720e4c9609'
down_revision: Union[str, Sequence[str], None] = 'abbf081957d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='用户头像URL',
               existing_server_default=sa.text("'https://projeck.obs.cn-south-1.myhuaweicloud.com/UserIcon/1/20250706135900_avatar.jpg'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='用户头像URL',
               existing_server_default=sa.text("'https://projeck.obs.cn-south-1.myhuaweicloud.com/UserIcon/1/20250706135900_avatar.jpg'::character varying"))
    # ### end Alembic commands ###
