"""add new column alt into table Gallery

Revision ID: 546c36fb5ce2
Revises: 76fa95282313
Create Date: 2026-01-27 09:51:30.713901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546c36fb5ce2'
down_revision: Union[str, Sequence[str], None] = '76fa95282313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery', sa.Column('alt', sa.String(), nullable=False, comment='图片描述'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gallery', 'alt')
    # ### end Alembic commands ###
