"""fix update error in Blog

Revision ID: 55027cab4f2a
Revises: 86399164cf3b
Create Date: 2026-02-01 17:25:15.559625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55027cab4f2a'
down_revision: Union[str, Sequence[str], None] = '86399164cf3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'state')
    op.drop_column('blogs', 'type')
    op.drop_column('music', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('state', sa.VARCHAR(length=7), autoincrement=False, nullable=True, comment='0正常 1已删除 2被封禁'))
    op.add_column('blogs', sa.Column('type', postgresql.ENUM('draft', 'publish', name='blogenum'), autoincrement=False, nullable=False, comment='0音乐博客 1博客'))
    op.add_column('blogs', sa.Column('state', postgresql.ENUM('normal', 'delete', 'ban', name='blogstateenum'), autoincrement=False, nullable=False, comment='0草稿 1正常 2已删除 3被封禁'))
    # ### end Alembic commands ###
