"""fix error in ImgEnum again

Revision ID: 5c4dcc3a69bb
Revises: 9597ac94d927
Create Date: 2026-01-27 11:53:57.627890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c4dcc3a69bb'
down_revision: Union[str, Sequence[str], None] = '9597ac94d927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Column('type', sa.String(), nullable=False, comment='类型'),
    op.alter_column('gallery', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('file', 'pic', name='imgenum'),
               existing_comment='类型',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gallery', 'type',
               existing_type=sa.Enum('file', 'pic', name='imgenum'),
               type_=sa.VARCHAR(),
               existing_comment='类型',
               existing_nullable=False)
    # ### end Alembic commands ###
