"""rebuild reksab cause by database confused accident

Revision ID: 6ba65a2f21da
Revises: 
Create Date: 2026-01-28 08:56:31.236062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba65a2f21da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cycle=False), nullable=False, comment='博客id'),
    sa.Column('type', sa.Enum('draft', 'publish', name='blogenum'), nullable=False, comment='0草稿 1正式'),
    sa.Column('state', sa.Enum('normal', 'delete', 'ban', name='blogstateenum'), nullable=False, comment='0正常 1已删除 2被封禁'),
    sa.Column('title', sa.String(length=40), nullable=False, comment='博客标题'),
    sa.Column('content', sa.TEXT(), nullable=False, comment='博客内容'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('rid', sa.Integer(), nullable=False, comment='用户通用id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogs_id'), 'blogs', ['id'], unique=True)
    op.create_index(op.f('ix_blogs_rid'), 'blogs', ['rid'], unique=False)
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cycle=False), nullable=False, comment='图片id'),
    sa.Column('type', sa.Enum('file', 'pic', 'avatar', name='imgenum'), nullable=False, comment='0文件图片 1普通图片'),
    sa.Column('rid', sa.Integer(), nullable=False, comment='用户通用id'),
    sa.Column('url', sa.String(), nullable=False, comment='图片链接'),
    sa.Column('alt', sa.String(), nullable=False, comment='图片描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('md5', sa.String(length=32), nullable=True, comment='文件哈希'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_id'), 'gallery', ['id'], unique=True)
    op.create_index(op.f('ix_gallery_md5'), 'gallery', ['md5'], unique=True)
    op.create_index(op.f('ix_gallery_rid'), 'gallery', ['rid'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cycle=False), nullable=False, comment='标签id'),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=True)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='用户UUID'),
    sa.Column('reks_id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cycle=False), nullable=False, comment='用户通用id'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('hashed_password', sa.String(length=255), nullable=True, comment='哈希密码'),
    sa.Column('username', sa.String(length=35), nullable=False, comment='用户名'),
    sa.Column('gender', sa.Enum('unknown', 'male', 'female', name='genderenum'), server_default='unknown', nullable=False, comment='0未知 1男 2女'),
    sa.Column('email', sa.String(length=320), nullable=True, comment='电子邮箱'),
    sa.Column('type', sa.Enum('ordinary', 'admin', 'supreme', name='usertypeenum'), nullable=False, comment='0用户 1管理员 2超管'),
    sa.Column('status', sa.Enum('active', 'danger', 'block', name='statusenum'), nullable=False, comment='0正常 1危险 2封禁'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间 NULL=未删除'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='用户头像URL'),
    sa.Column('signature', sa.String(length=255), server_default='这个人很懒，什么都没留下', nullable=False, comment='用户个性签名'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_reks_id'), 'users', ['reks_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('blogs_tags',
    sa.Column('blog_id', sa.Integer(), nullable=False, comment='Blog ID'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='Tag ID'),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs_tags')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_reks_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_gallery_rid'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_md5'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_id'), table_name='gallery')
    op.drop_table('gallery')
    op.drop_index(op.f('ix_blogs_rid'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_id'), table_name='blogs')
    op.drop_table('blogs')
    # ### end Alembic commands ###
