"""manual add gallery.type

Revision ID: 6c2fa5c94ba6
Revises: 5c4dcc3a69bb
Create Date: 2026-01-27 12:08:04.244570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c2fa5c94ba6'
down_revision: Union[str, Sequence[str], None] = '5c4dcc3a69bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gallery', 'type',
               existing_type=postgresql.ENUM('file', 'pic', name='imgenum'),
               comment='0文件图片 1普通图片',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gallery', 'type',
               existing_type=postgresql.ENUM('file', 'pic', name='imgenum'),
               comment=None,
               existing_comment='0文件图片 1普通图片',
               existing_nullable=False)
    # ### end Alembic commands ###
