"""change sex into gender;add signature into user

Revision ID: 76c3adcfee08
Revises: e4771d4a4bee
Create Date: 2025-12-25 09:30:11.830859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76c3adcfee08'
down_revision: Union[str, Sequence[str], None] = 'e4771d4a4bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',
                  sa.Column('gender', sa.Enum('unknown', 'male', 'female', name='genderenum'), server_default='unknown',
                            nullable=False, comment='0未知 1男 2女'))
    op.add_column('users',
                  sa.Column('signature', sa.String(length=255), server_default='这个人很懒，什么都没留下', nullable=True,
                            comment='用户个性签名'))
    op.drop_column('users', 'sex')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',
                  sa.Column('sex', postgresql.ENUM('unknown', 'male', 'female', name='sexenum'), autoincrement=False,
                            nullable=False, comment='0未知 1男 2女'))
    op.drop_column('users', 'signature')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
