"""add new column url into table Gallery

Revision ID: 76fa95282313
Revises: 99d99212bd5f
Create Date: 2026-01-27 09:48:12.557182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76fa95282313'
down_revision: Union[str, Sequence[str], None] = '99d99212bd5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery', sa.Column('url', sa.String(), nullable=False, comment='图片链接'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gallery', 'url')
    # ### end Alembic commands ###
