"""update table blog column 'rid' into ForeginKey

Revision ID: 77d372f8dfc3
Revises: bbc1264adbf0
Create Date: 2026-06-03 14:20:03.065841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d372f8dfc3'
down_revision: Union[str, Sequence[str], None] = 'bbc1264adbf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'blogs', 'users', ['rid'], ['reks_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    # ### end Alembic commands ###
