"""update Table blogs_tags

Revision ID: 7ae4a81032a3
Revises: 6ba65a2f21da
Create Date: 2026-01-29 11:41:50.064851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae4a81032a3'
down_revision: Union[str, Sequence[str], None] = '6ba65a2f21da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blogs_tags_blog_id'), 'blogs_tags', ['blog_id'], unique=False)
    op.create_index(op.f('ix_blogs_tags_tag_id'), 'blogs_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogs_tags_tag_id'), table_name='blogs_tags')
    op.drop_index(op.f('ix_blogs_tags_blog_id'), table_name='blogs_tags')
    # ### end Alembic commands ###
