"""update Table blog and music

Revision ID: 86399164cf3b
Revises: 3b5b02dbfc60
Create Date: 2026-02-01 17:11:26.379223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86399164cf3b'
down_revision: Union[str, Sequence[str], None] = '3b5b02dbfc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'type',
               existing_type=postgresql.ENUM('draft', 'publish', name='blogenum'),
               comment='0音乐博客 1博客',
               existing_comment='0草稿 1正式',
               existing_nullable=False)
    op.alter_column('blogs', 'state',
               existing_type=postgresql.ENUM('normal', 'delete', 'ban', name='blogstateenum'),
               comment='0草稿 1正常 2已删除 3被封禁',
               existing_comment='0正常 1已删除 2被封禁',
               existing_nullable=False)
    op.alter_column('music', 'state',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('draft', 'publish', 'delete', 'ban', name='blogstateenum', native_enum=False),
               nullable=True,
               existing_comment='0正常 1已删除 2被封禁')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'state',
               existing_type=sa.Enum('draft', 'publish', 'delete', 'ban', name='blogstateenum', native_enum=False),
               type_=sa.VARCHAR(length=6),
               nullable=False,
               existing_comment='0正常 1已删除 2被封禁')
    op.alter_column('blogs', 'state',
               existing_type=postgresql.ENUM('normal', 'delete', 'ban', name='blogstateenum'),
               comment='0正常 1已删除 2被封禁',
               existing_comment='0草稿 1正常 2已删除 3被封禁',
               existing_nullable=False)
    op.alter_column('blogs', 'type',
               existing_type=postgresql.ENUM('draft', 'publish', name='blogenum'),
               comment='0草稿 1正式',
               existing_comment='0音乐博客 1博客',
               existing_nullable=False)
    # ### end Alembic commands ###
