"""update md5 nullable

Revision ID: 8e311e3101af
Revises: 2756079c29ae
Create Date: 2026-01-27 14:05:51.183433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e311e3101af'
down_revision: Union[str, Sequence[str], None] = '2756079c29ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery', sa.Column('md5', sa.String(length=32), nullable=False, comment='文件哈希'))
    op.create_index(op.f('ix_gallery_md5'), 'gallery', ['md5'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_md5'), table_name='gallery')
    op.drop_column('gallery', 'md5')
    # ### end Alembic commands ###
