"""add table usersettings into database

Revision ID: 8f5bbadf9fca
Revises: c9698173e86e
Create Date: 2026-05-08 16:13:15.779216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f5bbadf9fca'
down_revision: Union[str, Sequence[str], None] = 'c9698173e86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersettings',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cycle=False), nullable=False, comment='用户设置id'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户id'),
    sa.Column('default_visibility', sa.Enum('public', 'follower', 'private', name='visitenum'), nullable=False, comment='全局默认可见性'),
    sa.Column('home_visibility', sa.Enum('public', 'follower', 'private', name='visitenum'), nullable=False, comment='我的主页可见性'),
    sa.Column('posts_visibility', sa.Enum('public', 'follower', 'private', name='visitenum'), nullable=False, comment='我的发布可见性'),
    sa.Column('favorites_visibility', sa.Enum('public', 'follower', 'private', name='visitenum'), nullable=False, comment='我的收藏可见性'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.reks_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersettings_id'), 'usersettings', ['id'], unique=True)
    op.create_index(op.f('ix_usersettings_user_id'), 'usersettings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usersettings_user_id'), table_name='usersettings')
    op.drop_index(op.f('ix_usersettings_id'), table_name='usersettings')
    op.drop_table('usersettings')
    # ### end Alembic commands ###
