"""fix new database error

Revision ID: 9959c72c980d
Revises: 8f5bbadf9fca
Create Date: 2026-05-25 15:22:53.291464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9959c72c980d'
down_revision: Union[str, Sequence[str], None] = '8f5bbadf9fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Align enum values with src/orm/__init__.py (PostgreSQL doesn't auto-update enums).
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_type t
                JOIN pg_enum e ON t.oid = e.enumtypid
                WHERE t.typname = 'blogstateenum' AND e.enumlabel = 'normal'
            ) THEN
                ALTER TYPE blogstateenum RENAME VALUE 'normal' TO 'publish';
            END IF;
        END $$;
        """
    )
    op.execute("ALTER TYPE blogstateenum ADD VALUE IF NOT EXISTS 'draft'")
    op.execute("ALTER TYPE blogstateenum ADD VALUE IF NOT EXISTS 'publish'")
    op.execute("ALTER TYPE blogstateenum ADD VALUE IF NOT EXISTS 'delete'")
    op.execute("ALTER TYPE blogstateenum ADD VALUE IF NOT EXISTS 'ban'")

    op.execute("ALTER TYPE blogenum ADD VALUE IF NOT EXISTS 'mblog'")
    op.execute("ALTER TYPE blogenum ADD VALUE IF NOT EXISTS 'blog'")
    op.execute("ALTER TYPE blogenum ADD VALUE IF NOT EXISTS 'notice'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Downgrade for enum values is intentionally a no-op (PostgreSQL doesn't support DROP VALUE).
    pass
    # ### end Alembic commands ###
