"""create table Gallery

Revision ID: 99d99212bd5f
Revises: ab94c999a693
Create Date: 2026-01-27 09:26:40.257689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d99212bd5f'
down_revision: Union[str, Sequence[str], None] = 'ab94c999a693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cycle=False), nullable=False, comment='图片id'),
    sa.Column('type', sa.String(), nullable=False, comment='类型'),
    sa.Column('rid', sa.Integer(), nullable=False, comment='用户通用id'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_id'), 'gallery', ['id'], unique=True)
    op.create_index(op.f('ix_gallery_rid'), 'gallery', ['rid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_rid'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_id'), table_name='gallery')
    op.drop_table('gallery')
    # ### end Alembic commands ###
