"""init user table again

Revision ID: a72b9825291a
Revises: bb4e2001cf7e
Create Date: 2025-12-10 12:55:26.610621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a72b9825291a'
down_revision: Union[str, Sequence[str], None] = 'bb4e2001cf7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='用户ID'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='哈希密码'),
    sa.Column('username', sa.String(length=35), nullable=False, comment='用户名'),
    sa.Column('sex', sa.Enum('unknown', 'male', 'female', name='sexenum'), nullable=False, comment='0未知 1男 2女'),
    sa.Column('email', sa.String(length=320), nullable=True, comment='电子邮箱'),
    sa.Column('type', sa.Enum('ordinary', 'admin', 'supreme', name='usertypeenum'), nullable=False, comment='0用户 1管理员 2超管'),
    sa.Column('status', sa.Enum('active', 'blocked', 'inactive', name='statusenum'), nullable=False, comment='0正常 1禁用 2未激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间 NULL=未删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
