"""update table Tag and table Blog

Revision ID: ab94c999a693
Revises: 145cb0232ecf
Create Date: 2026-01-26 21:23:05.211964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab94c999a693'
down_revision: Union[str, Sequence[str], None] = '145cb0232ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('rid', sa.Integer(), nullable=False, comment='用户通用id'))
    op.create_index(op.f('ix_blogs_rid'), 'blogs', ['rid'], unique=False)
    op.add_column('tags', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'updated_at')
    op.drop_index(op.f('ix_blogs_rid'), table_name='blogs')
    op.drop_column('blogs', 'rid')
    # ### end Alembic commands ###
