"""change signature into NOTNULL

Revision ID: abbf081957d0
Revises: 76c3adcfee08
Create Date: 2025-12-25 09:47:41.644095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abbf081957d0'
down_revision: Union[str, Sequence[str], None] = '76c3adcfee08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'signature',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='用户个性签名',
               existing_server_default=sa.text("'这个人很懒，什么都没留下'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'signature',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='用户个性签名',
               existing_server_default=sa.text("'这个人很懒，什么都没留下'::character varying"))
    # ### end Alembic commands ###
