"""create Table Contact, Conversation, Message

Revision ID: aef4f9363f70
Revises: 094376ce390a
Create Date: 2026-02-25 10:51:55.820404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef4f9363f70'
down_revision: Union[str, Sequence[str], None] = '094376ce390a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='联系人记录UUID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关注 UUID'),
    sa.Column('followed_user_id', sa.UUID(), nullable=False, comment='被关注 UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='关注时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True, comment='关注动态已读游标时间'),
    sa.CheckConstraint('user_id <> followed_user_id', name='ck_contacts_not_self'),
    sa.ForeignKeyConstraint(['followed_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'followed_user_id', name='uq_contacts_pair')
    )
    op.create_index(op.f('ix_contacts_followed_user_id'), 'contacts', ['followed_user_id'], unique=False)
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='会话UUID'),
    sa.Column('user_a_id', sa.UUID(), nullable=False, comment='会话用户A'),
    sa.Column('user_b_id', sa.UUID(), nullable=False, comment='会话用户B'),
    sa.Column('last_message', sa.String(length=1000), nullable=True, comment='最后一条消息预览'),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True, comment='最后消息时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint('user_a_id <> user_b_id', name='ck_conversations_not_self'),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_user_a_id'), 'conversations', ['user_a_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_b_id'), 'conversations', ['user_b_id'], unique=False)
    op.create_index('uq_conversations_user_pair_norm', 'conversations', [sa.literal_column('LEAST(user_a_id, user_b_id)'), sa.literal_column('GREATEST(user_a_id, user_b_id)')], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='消息UUID'),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='会话UUID'),
    sa.Column('sender_id', sa.UUID(), nullable=False, comment='发送者UUID'),
    sa.Column('content', sa.Text(), nullable=False, comment='文本消息内容'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='发送时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间 NULL=未删除'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_deleted_at'), 'messages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_deleted_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('uq_conversations_user_pair_norm', table_name='conversations')
    op.drop_index(op.f('ix_conversations_user_b_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_user_a_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_followed_user_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
