"""fix update error in Blog 2

Revision ID: b032c5c9cd5d
Revises: a795e69d4073
Create Date: 2026-02-01 17:41:43.592098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b032c5c9cd5d'
down_revision: Union[str, Sequence[str], None] = 'a795e69d4073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # handle Error not created
    blogenum = postgresql.ENUM('mblog', 'blog', name='blogenum')
    blogenum.create(op.get_bind(), checkfirst=True)

    blogstateenum = postgresql.ENUM('draft', 'publish', 'delete', 'ban', name='blogstateenum')
    blogstateenum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('type', sa.Enum('mblog', 'blog', name='blogenum'), nullable=False, comment='0音乐博客 1博客'))
    op.add_column('blogs', sa.Column('state', sa.Enum('draft', 'publish', 'delete', 'ban', name='blogstateenum'), nullable=False, comment='0草稿 1正常 2已删除 3被封禁'))
    op.add_column('music', sa.Column('state', sa.Enum('draft', 'publish', 'delete', 'ban', name='blogstateenum', native_enum=False), nullable=True, comment='0正常 1已删除 2被封禁'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music', 'state')
    op.drop_column('blogs', 'state')
    op.drop_column('blogs', 'type')
    # ### end Alembic commands ###
