"""add /notification/ into blogenum

Revision ID: b79d15c7022b
Revises: 28fb06cd30f3
Create Date: 2026-04-01 13:37:59.812226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b79d15c7022b'
down_revision: Union[str, Sequence[str], None] = '28fb06cd30f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'type',
               existing_type=postgresql.ENUM('mblog', 'blog', name='blogenum'),
               comment='0音乐博客 1博客 2通知',
               existing_comment='0音乐博客 1博客',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'type',
               existing_type=postgresql.ENUM('mblog', 'blog', name='blogenum'),
               comment='0音乐博客 1博客',
               existing_comment='0音乐博客 1博客 2通知',
               existing_nullable=False)
    # ### end Alembic commands ###
