"""remove type 'mblog'

Revision ID: bbc1264adbf0
Revises: 05328f9debe5
Create Date: 2026-06-01 17:10:47.078039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbc1264adbf0'
down_revision: Union[str, Sequence[str], None] = '05328f9debe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_rid'), table_name='playlist')
    op.drop_table('playlists_music')
    op.drop_table('playlist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists_music',
    sa.Column('playlist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('music_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], name=op.f('playlists_music_music_id_fkey')),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], name=op.f('playlists_music_playlist_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'music_id', name=op.f('playlists_music_pkey'))
    )
    op.create_table('playlist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='歌单id'),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='歌单标题'),
    sa.Column('cover', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='封面URL'),
    sa.Column('desc', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='简介'),
    sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否私密'),
    sa.Column('rid', sa.INTEGER(), autoincrement=False, nullable=False, comment='用户通用id'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rid'], ['users.reks_id'], name=op.f('playlist_rid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('playlist_pkey'))
    )
    op.create_index(op.f('ix_playlist_rid'), 'playlist', ['rid'], unique=False)
    # ### end Alembic commands ###
