"""add rid in user table

Revision ID: c7c70402fb72
Revises: 5cf143968431
Create Date: 2025-12-11 14:21:03.355716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c70402fb72'
down_revision: Union[str, Sequence[str], None] = '5cf143968431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment='用户UUID',
               existing_comment='用户ID',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment='用户ID',
               existing_comment='用户UUID',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###
