"""update Table Music Structure

Revision ID: c9698173e86e
Revises: dc68ab9408c4
Create Date: 2026-04-02 15:11:11.889897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9698173e86e'
down_revision: Union[str, Sequence[str], None] = 'dc68ab9408c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'type',
               existing_type=sa.VARCHAR(length=8),
               nullable=False,
               existing_comment='素材0 歌曲1')
    op.alter_column('music', 'related',
               existing_type=sa.VARCHAR(length=8),
               nullable=False,
               existing_comment='普通用户0 官方（管理员）1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'related',
               existing_type=sa.VARCHAR(length=8),
               nullable=True,
               existing_comment='普通用户0 官方（管理员）1')
    op.alter_column('music', 'type',
               existing_type=sa.VARCHAR(length=8),
               nullable=True,
               existing_comment='素材0 歌曲1')
    # ### end Alembic commands ###
