"""add md5 nullable in Table Gallery

Revision ID: d21f9256d4ac
Revises: 8e311e3101af
Create Date: 2026-01-27 14:08:43.014220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21f9256d4ac'
down_revision: Union[str, Sequence[str], None] = '8e311e3101af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery', sa.Column('md5', sa.String(length=32), nullable=True, comment='文件哈希'))
    op.create_index(op.f('ix_gallery_md5'), 'gallery', ['md5'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_md5'), table_name='gallery')
    op.drop_column('gallery', 'md5')
    # ### end Alembic commands ###
