"""调整user的部分属性:password调整为nullable

Revision ID: d236ae013e13
Revises: a72b9825291a
Create Date: 2025-12-10 14:01:16.138544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd236ae013e13'
down_revision: Union[str, Sequence[str], None] = 'a72b9825291a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='哈希密码')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='哈希密码')
    # ### end Alembic commands ###
