"""add --related and --type into Table Music

Revision ID: dc68ab9408c4
Revises: b79d15c7022b
Create Date: 2026-04-02 14:47:10.831883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc68ab9408c4'
down_revision: Union[str, Sequence[str], None] = 'b79d15c7022b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('type', sa.Enum('material', 'song', name='musictypeenum', native_enum=False), nullable=True, comment='素材0 歌曲1'))
    op.add_column('music', sa.Column('related', sa.Enum('normal', 'official', name='musicrelatedenum', native_enum=False), nullable=True, comment='普通用户0 官方（管理员）1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music', 'related')
    op.drop_column('music', 'type')
    # ### end Alembic commands ###
