"""add avatar in user table

Revision ID: e4771d4a4bee
Revises: 3a49b56ecea4
Create Date: 2025-12-15 10:10:14.609121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4771d4a4bee'
down_revision: Union[str, Sequence[str], None] = '3a49b56ecea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=255), server_default='https://projeck.obs.cn-south-1.myhuaweicloud.com/UserIcon/1/20250706135900_avatar.jpg', nullable=False, comment='用户头像URL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
