"""remove relationship on User between PlayList

Revision ID: f94d5a7bbe75
Revises: 77d372f8dfc3
Create Date: 2026-06-04 15:59:18.525403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94d5a7bbe75'
down_revision: Union[str, Sequence[str], None] = '77d372f8dfc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
